# Samuel Allegretto
## Week 11 - 11/05/2020
### Python Numpy Universal Functions

In [5]:
import numpy as np

arr1 = [1,2,3,4,5,6,7,8,9]

arr2 = [11,12,13,14,15,16,17,18]

z=[]

for i, j in zip(arr1,arr2):
    z.append(i + j)
    
z

[12, 14, 16, 18, 20, 22, 24, 26]

In [7]:
#zip

fname = ('Alice', 'Bob', 'Christy')
lname = ('Charlie','Clark','Robert')

flname = zip(fname,lname)

print(tuple(flname))

(('Alice', 'Charlie'), ('Bob', 'Clark'), ('Christy', 'Robert'))


In [8]:
lst1 = [1,2,3,4,5]
lst2 = [10,11,12,13,14]

print(list(zip(lst1,lst2)))

[(1, 10), (2, 11), (3, 12), (4, 13), (5, 14)]


In [9]:
import numpy as np

arr = np.arange(21)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [11]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [16]:
arr1 = np.random.randn(10)
arr1

array([ 0.34297222,  1.48132772, -0.14124191,  0.46286017, -0.30969554,
       -0.58792906, -0.03253991, -1.40037688,  1.77050418, -0.08173166])

In [14]:
arr2 = np.random.randn(10)
arr2

array([-1.9515638 , -2.07454212, -1.38560632,  0.74554307,  0.93431455,
       -1.12160916, -0.04673691,  1.00625163, -0.52964343, -0.22842359])

In [17]:
np.add(arr1,arr2)

array([-1.60859159, -0.5932144 , -1.52684823,  1.20840324,  0.62461901,
       -1.70953821, -0.07927682, -0.39412524,  1.24086075, -0.31015525])

In [18]:
np.maximum(arr1,arr2)

array([ 0.34297222,  1.48132772, -0.14124191,  0.74554307,  0.93431455,
       -0.58792906, -0.03253991,  1.00625163,  1.77050418, -0.08173166])

In [20]:
#np.where
arr = np.arange(9).reshape(3,3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
print(arr < 4)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [24]:
np.where(arr<4,-1,-2)

array([[-1, -1, -1],
       [-1, -2, -2],
       [-2, -2, -2]])

In [26]:
np.where((arr < 4) & (arr >2),-1,-2)

array([[-2, -2, -2],
       [-1, -2, -2],
       [-2, -2, -2]])

In [28]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

arr_b = np.array([True,False,True,True,False])

print(arr1)
print(arr2)
print(arr_b)

print(list(zip(arr1,arr2)))

[1 2 3 4 5]
[10 20 30 40 50]
[ True False  True  True False]
[(1, 10), (2, 20), (3, 30), (4, 40), (5, 50)]


In [29]:
#using list comprehension
arr3 = [r1 if c else r2 for r1,r2, c in zip(arr1,arr2,arr_b)]

arr3

[1, 20, 3, 4, 50]

In [30]:
#using np.where
arr3 = np.where(arr_b,arr1,arr2)

arr3

array([ 1, 20,  3,  4, 50])

In [4]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
cond = np.array ([[True,False],[True,False]])

np.where(cond,arr1,arr2)

array([[1, 6],
       [3, 8]])

In [7]:
np.where([[True,False],[True,False]], [[5,6],[7,8]], [[1,2],[3,4]])

array([[5, 2],
       [7, 4]])

In [8]:
from numpy.random import randn
arr = randn(5,5)
arr

array([[-1.36031011,  0.50594612,  0.08502644,  0.35024827, -0.51044634],
       [ 1.10939644, -1.99554499,  0.81736219,  0.25067811,  0.17502506],
       [-0.21789952,  0.69486884,  0.03483322, -1.62775803, -0.43870933],
       [ 0.04963169,  0.50049733, -0.30709674, -2.09634811,  1.2244934 ],
       [-2.43880294,  0.59528101,  0.2845069 ,  0.5551892 ,  0.14697174]])

In [10]:
np.where(arr<0, 0,arr)

array([[0.        , 0.50594612, 0.08502644, 0.35024827, 0.        ],
       [1.10939644, 0.        , 0.81736219, 0.25067811, 0.17502506],
       [0.        , 0.69486884, 0.03483322, 0.        , 0.        ],
       [0.04963169, 0.50049733, 0.        , 0.        , 1.2244934 ],
       [0.        , 0.59528101, 0.2845069 , 0.5551892 , 0.14697174]])

In [12]:
arr_b = np.array([True,False,True,False,False])

arr_b.any()

True

In [13]:
arr_b.all()

False

In [14]:
fruits = np.array (['Apple','Cherry','Apple','Orange','Cherry','Banana'])

np.unique(fruits)

array(['Apple', 'Banana', 'Cherry', 'Orange'], dtype='<U6')

In [16]:
np.in1d(['Apple','Cherry','Grape'],fruits)

array([ True,  True, False])

In [17]:
#Statistical Measures 

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr)


(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
arr.sum()

45

In [19]:
arr.sum(0)

array([12, 15, 18])

In [20]:
arr.sum(1)

array([ 6, 15, 24])

In [21]:
arr.sum(2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [22]:
print(arr)
np.sum(arr, axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [23]:
print(arr)
np.sum(arr, axis = 1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [25]:
print(arr)
np.sum(arr, axis = None)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [27]:
arr.mean()

5.0

In [29]:
print(arr)
arr.mean(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [31]:
np.mean(arr,axis = 0)


array([4., 5., 6.])

In [32]:
np.mean(arr,axis = 1)

array([2., 5., 8.])

In [33]:
arr.var()

6.666666666666667

In [34]:
arr.std()

2.581988897471611

In [35]:
arr = np.array ([3,6,8,1,9,10,3,5,63,9,12,10,15,11,14])

arr.sort()

arr

array([ 1,  3,  3,  5,  6,  8,  9,  9, 10, 10, 11, 12, 14, 15, 63])

In [36]:
#identity array 

i = np.eye(5)

i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
a = np.arange(25).reshape((5,5))

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
a * i

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  0., 12.,  0.,  0.],
       [ 0.,  0.,  0., 18.,  0.],
       [ 0.,  0.,  0.,  0., 24.]])

In [44]:
i = np.eye(2)
print(i)

a = np.arange(4).reshape((2,2))

a * 1

[[1. 0.]
 [0. 1.]]


array([[0, 1],
       [2, 3]])

In [45]:
m = np.mat([[1,2],[3,4]])

m

matrix([[1, 2],
        [3, 4]])

In [46]:
m * i

matrix([[1., 2.],
        [3., 4.]])

In [49]:
#transpose 

arr = np.array([[1,2,3,4],[5,6,7,8]])

print (arr.shape)
print(arr)
print('--------------')

t = arr.T

t

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
--------------


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [51]:
arr.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [52]:
arr.transpose((0,1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
arr.transpose((1,0))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [54]:
arr_3d = np.arange(20).reshape((2,5,2))

print(arr_3d)
print(arr_3d.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
(2, 5, 2)


In [55]:
arr_3d.transpose((0,1,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [56]:
arr_3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]],

       [[ 4,  5],
        [14, 15]],

       [[ 6,  7],
        [16, 17]],

       [[ 8,  9],
        [18, 19]]])

In [57]:
arr_3d.transpose((2,1,0))

array([[[ 0, 10],
        [ 2, 12],
        [ 4, 14],
        [ 6, 16],
        [ 8, 18]],

       [[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]]])

In [58]:
np.random.random((4,4))

array([[0.1224966 , 0.56473655, 0.03163534, 0.09909778],
       [0.99687397, 0.79140894, 0.99173525, 0.16046859],
       [0.63489469, 0.4845673 , 0.84434585, 0.22120264],
       [0.22652188, 0.2203432 , 0.17375816, 0.01939762]])

In [59]:
from numpy.random import random
random((4,4))
 

array([[0.64912108, 0.09832164, 0.86055795, 0.07997315],
       [0.10369532, 0.1035493 , 0.63692334, 0.3984627 ],
       [0.37733153, 0.6595311 , 0.19176542, 0.73387214],
       [0.77780608, 0.61634426, 0.21138798, 0.76784947]])

In [61]:
from numpy.random import randn
randn(5,5)

array([[ 0.70320939,  0.08506539, -0.36134588, -0.55298929, -0.91753884],
       [-0.72707637, -0.69015795,  0.04859658, -0.02259083, -0.89851004],
       [ 1.13608311, -0.5145348 ,  0.39742326,  0.67147168,  0.14988485],
       [ 0.47276432, -0.84946887,  0.25596814, -0.7678889 , -1.16555947],
       [ 1.3363755 , -0.88877723,  0.5714914 ,  0.21860791, -0.79529837]])

In [62]:
randn(5)

array([-0.82862638, -1.26546295, -0.56755172, -1.14600709,  0.87770306])

In [63]:
np.random.randint(10,50)

28

In [65]:
website = "//docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"

import webbrowser
webbrowser.open(website)

True

In [66]:
import pandas as pd