# Samuel Allegretto
## Week 10 - 10/29/2020
### Python NumPy - Processing arrays


In [1]:
import numpy as np

In [2]:
my_list = [11,22,33,44,55,66,77]
print(my_list)

[11, 22, 33, 44, 55, 66, 77]


In [3]:
my_arr = np.array(my_list)

In [4]:
print(my_arr.dtype)

int32


In [7]:
fruits = ['Orange','Apple','Cherry','Grape']

my_strArr = np.array(fruits)

In [8]:
print(my_strArr.dtype)

<U6


In [9]:
my_arr2 = np.array([11,22,33,44,55], dtype ='S')

In [10]:
print(my_arr2.dtype)

|S2


In [11]:
my_arr2 = np.array([1,2,3,4,5], dtype ='S')

print(my_arr2.dtype)

|S1


In [18]:
my_arr3 = np.array([5,6,7,8,9], dtype = 'i8')

In [20]:
print(my_arr3.dtype)
print(my_arr.dtype)

int64
int32


In [16]:
my_arr = np.array(['1','2','3','4','5'], dtype = 'i')

In [17]:
print(my_arr)

[1 2 3 4 5]


In [21]:
my_errArr = np.array(['1','2','C','4','5'], dtype = 'i')

ValueError: invalid literal for int() with base 10: 'C'

In [22]:
scores = [78.5,88.9,90.3,89.9]

my_arr = np.array(scores)

In [23]:
print(my_arr)

[78.5 88.9 90.3 89.9]


In [24]:
arr = my_arr.astype('i')

In [25]:
print(arr)

[78 88 90 89]


In [26]:
arr = np.array([1,0,0,3,4,5,6,7,0])

In [27]:
print(arr.dtype)

int32


In [34]:
bool_arr=arr.astype(bool)

In [33]:
print(arr)
print(bool_arr)

[1 0 0 3 4 5 6 7 0]
[ True False False  True  True  True  True  True False]


In [35]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]

my_arr = np.array(my_list)

print(my_arr)
print(my_arr.ndim)

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


In [36]:
#numpy built-in functions to generate arrays from excisting arrays
# copy and view, instead of using = 

my_lst = [11,12,13,14,15]

arr = np.array(my_lst)
c_arr = arr.copy()

print(arr)
print(c_arr)

[11 12 13 14 15]
[11 12 13 14 15]


In [37]:
arr[3] = 4
print(arr)
print(c_arr)

[11 12 13  4 15]
[11 12 13 14 15]


In [40]:
#view
my_lst = [11,12,13,14,15]

arr = np.array(my_lst)
v_arr = arr.view()

print(arr)
print(c_arr)


[11 12 13 14 15]
[11 12 13  4 15]


In [41]:
arr[3] = 4
print(arr)
print(v_arr)

[11 12 13  4 15]
[11 12 13  4 15]


In [42]:
arr[2] = 3
print(arr)
print(v_arr)

[11 12  3  4 15]
[11 12  3  4 15]


In [43]:
print(c_arr.base)
print(v_arr.base)

[11 12 13  4 15]
[11 12  3  4 15]


In [44]:
#Shape method gives the number o elements in each dimension


In [47]:
lst1 = [1,2,3,4,5]
lst2 = [11,22,33,44,55]

my_list = [lst1,lst2]

my_arr = np.array(my_list)
print(my_arr)
print(my_arr.ndim)
my_arr.shape

[[ 1  2  3  4  5]
 [11 22 33 44 55]]
2


(2, 5)

In [48]:
# shape return 2 dimesnions and each dimension has 5 elements 

In [49]:
arr = np.array(lst1, ndmin=4)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[1 2 3 4 5]]]]
4
(1, 1, 1, 5)


In [50]:
arr = np.array(lst1, ndmin=6)

print(arr)
print(arr.ndim)
print(arr.shape)

[[[[[[1 2 3 4 5]]]]]]
6
(1, 1, 1, 1, 1, 5)


In [ ]:
# each index in the shape tells the number of elements in that dimension